-- شطرنج العرب - Supabase schema v2
create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 60),
  mobile text not null unique
    check (mobile ~ '^(05[0-9]{8}|[+][1-9][0-9]{7,14})$'),
  region text not null,
  city text not null,
  category text not null default 'open'
    check (category in ('open','u18','u14','u10')),
  rating integer not null default 1500,
  rating_status text not null default 'provisional'
    check (rating_status in ('provisional','verified')),
  games_count integer not null default 0,
  wins integer not null default 0,
  draws integer not null default 0,
  losses integer not null default 0,
  status text not null default 'active'
    check (status in ('active','suspended')),
  created_at timestamptz not null default now()
);

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  region text,
  city text,
  time_control text not null default 'rapid',
  starts_at timestamptz,
  status text not null default 'draft'
    check (status in ('draft','open','running','finished')),
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid references public.tournaments(id) on delete set null,
  white_player uuid not null references public.players(id),
  black_player uuid not null references public.players(id),
  result text not null check (result in ('1-0','0-1','1/2-1/2')),
  rated boolean not null default true,
  played_at timestamptz not null default now(),
  check (white_player <> black_player)
);

create table if not exists public.rating_history (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  match_id uuid references public.matches(id) on delete set null,
  old_rating integer not null,
  new_rating integer not null,
  created_at timestamptz not null default now()
);

-- واجهة عامة لا تكشف رقم الجوال.
create or replace view public.public_players as
select id,name,region,city,category,rating,rating_status,games_count,wins,draws,losses,created_at
from public.players
where status='active';

-- التسجيل يتم عبر RPC حتى لا نمنح الزائر صلاحية قراءة أرقام الجوال.
-- نحافظ على صيغة الجوال السعودية القديمة ونقبل أرقام E.164 لبقية الدول العربية.
create or replace function public.register_player(
  p_name text,
  p_mobile text,
  p_region text,
  p_city text,
  p_category text default 'open'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id uuid;
  v_mobile text;
begin
  v_mobile := regexp_replace(btrim(coalesce(p_mobile,'')), '[[:space:]()-]', '', 'g');

  if v_mobile ~ '^00[1-9][0-9]{7,14}$' then
    v_mobile := chr(43) || substring(v_mobile from 3);
  end if;

  if v_mobile ~ '^[+]9665[0-9]{8}$' then
    v_mobile := '0' || substring(v_mobile from 5);
  elsif v_mobile !~ '^05[0-9]{8}$' and v_mobile !~ '^[+][1-9][0-9]{7,14}$' then
    raise exception 'invalid mobile';
  end if;

  insert into public.players(name,mobile,region,city,category)
  values(trim(p_name),v_mobile,trim(p_region),trim(p_city),p_category)
  returning id into new_id;
  return new_id;
end;
$$;

alter table public.players enable row level security;
alter table public.tournaments enable row level security;
alter table public.matches enable row level security;
alter table public.rating_history enable row level security;

-- لا قراءة مباشرة من players للزائر.
revoke all on table public.players from anon;
grant select on public.public_players to anon;
grant execute on function public.register_player(text,text,text,text,text) to anon;

create policy "public tournaments read"
on public.tournaments for select
to anon
using (status in ('open','running','finished'));

create policy "public matches read"
on public.matches for select
to anon
using (true);
