import { Chess, GAME_VARIANT } from 'https://cdn.jsdelivr.net/npm/cm-chess@4.0.0/+esm';
import { requirePlayer, rpc, supabase, escapeHtml } from '../../v2/platform/api.mjs';
import { loadBoardPreferences } from '../../v2/board/preferences.mjs';
import { getBoardTheme } from '../../v2/board/themes.mjs';
const $=id=>document.getElementById(id);const {player}=await requirePlayer();const board=$('variantBoard');let current=null,chess=null,selected=null,legal=[],poll=null,clockTimer=null,queueTimer=null,searching=false;
function theme(){const t=getBoardTheme(loadBoardPreferences().theme);board.style.setProperty('--board-light',t.light);board.style.setProperty('--board-dark',t.dark)}
function parse(fen){const m=new Map();fen.split(' ')[0].split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=Number(c);continue}m.set(`${String.fromCharCode(97+f)}${8-ri}`,{color:c===c.toUpperCase()?'w':'b',type:c.toLowerCase()});f++}});return m}
function squares(){const color=current?.my_color||'w',files=color==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=color==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function canMove(){return current?.status==='active'&&current.turn===current.my_color}
function renderBoard(){if(!chess)return;const pos=parse(chess.fen()),frag=document.createDocumentFragment();for(const name of squares()){const file=name.charCodeAt(0)-97,rank=Number(name[1]),sq=document.createElement('button');sq.type='button';sq.dataset.square=name;sq.className=`variant-square ${(file+rank)%2===1?'light':'dark'}${selected===name?' selected':''}`;const p=pos.get(name);if(p){const img=document.createElement('img');img.className='variant-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);for(const m of legal)board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}
function fmt(ms){ms=Math.max(0,Math.ceil(ms/1000));const m=Math.floor(ms/60),s=ms%60;return `${m}:${String(s).padStart(2,'0')}`}
function clocks(){if(!current)return{w:600000,b:600000};let w=Number(current.white_ms),b=Number(current.black_ms);if(current.status==='active'&&current.clock_anchor_at){const e=Math.max(0,Date.now()-Date.parse(current.clock_anchor_at));if(current.turn==='w')w-=e;else b-=e}return{w:Math.max(0,w),b:Math.max(0,b)}}
function renderMeta(){const c=clocks();$('whiteClock').textContent=fmt(c.w);$('blackClock').textContent=fmt(c.b);$('whiteName').textContent=current?.white_name||'الأبيض';$('blackName').textContent=current?.black_name||'الأسود';$('whiteMeta').textContent=current?` · ${current.white_player_id===player.id?'أنت':''}`:'';$('blackMeta').textContent=current?` · ${current.black_player_id===player.id?'أنت':''}`:'';$('whitePlayer').classList.toggle('turn',current?.status==='active'&&current.turn==='w');$('blackPlayer').classList.toggle('turn',current?.status==='active'&&current.turn==='b');$('variantDraw').disabled=!current||current.status!=='active';$('variantResign').disabled=!current||current.status!=='active';if(!current){$('variantStatus').textContent='اختر الزمن وابدأ البحث.';return}const opp=current.my_color==='w'?current.black_name:current.white_name;if(current.status==='active')$('variantStatus').textContent=`${current.turn===current.my_color?'دورك':'دور الخصم'} · ضد ${opp} · البداية #${current.start_index} · ${current.rated?'نقاط':'ودي'}`;else $('variantStatus').textContent=`انتهت المباراة ${current.result||''} · ${current.termination||''}`;if(current?.status==='active'&&(current.my_color===current.turn?c[current.turn]:c[current.turn])<=0)void invoke({action:'timeout',gameId:current.game_id}).then(()=>loadGame(current.game_id)).catch(()=>{})}
async function invoke(body){const {data,error}=await supabase.functions.invoke('variant-game-v3',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
async function listGames(){try{const rows=await rpc('v3_list_my_variant_games',{p_limit:30});$('variantGames').innerHTML=(rows||[]).map(g=>{const opp=g.my_color==='w'?g.black_name:g.white_name;return `<a class="variant-game-row" href="variants.html?game=${encodeURIComponent(g.game_id)}"><span><strong>${escapeHtml(opp)}</strong><small class="platform-muted"> · بداية #${g.start_index}</small></span><span class="platform-badge">${g.status==='active'?(g.turn===g.my_color?'دورك':'جارية'):(g.result||'منتهية')}</span></a>`}).join('')||'<div class="platform-empty">لا توجد مباريات Chess960 بعد.</div>';return rows||[]}catch(e){console.error(e);return[]}}
async function loadGame(id){if(!id){current=null;chess=new Chess({gameVariant:GAME_VARIANT.chess960});selected=null;legal=[];renderBoard();renderMeta();return}try{const rows=await rpc('v3_get_variant_game',{p_game_id:id});const g=Array.isArray(rows)?rows[0]:rows;if(!g)throw new Error('not found');current=g;chess=new Chess({fen:g.fen,gameVariant:GAME_VARIANT.chess960});selected=null;legal=[];renderBoard();renderMeta();await listGames();const u=new URL(location.href);if(u.searchParams.get('game')!==id){u.searchParams.set('game',id);history.replaceState({},'',u)}}catch(e){console.error(e);$('variantStatus').textContent='تعذر تحميل مباراة Chess960.'}}
async function makeMove(move){if(!current||!canMove())return;try{board.style.pointerEvents='none';await invoke({action:'move',gameId:current.game_id,expectedPly:current.ply,san:move.san});await loadGame(current.game_id)}catch(e){console.error(e);$('variantStatus').textContent=e.message?.includes('Illegal')?'نقلة غير قانونية.':'تعذر تنفيذ النقلة.';await loadGame(current.game_id)}finally{board.style.pointerEvents=''}}
board.addEventListener('click',async e=>{if(!chess||!canMove())return;const el=e.target.closest('.variant-square');if(!el)return;const sq=el.dataset.square,p=chess.piece(sq);if(!selected){if(p?.color===current.my_color){selected=sq;legal=chess.moves({square:sq,verbose:true});renderBoard()}return}if(sq===selected){selected=null;legal=[];renderBoard();return}const move=legal.find(m=>m.to===sq);if(move){selected=null;legal=[];await makeMove(move);return}if(p?.color===current.my_color){selected=sq;legal=chess.moves({square:sq,verbose:true});renderBoard()}else{selected=null;legal=[];renderBoard()}});
async function queue(){if(searching)return;searching=true;$('variantQueue').disabled=true;$('variantCancel').disabled=false;$('variantQueueState').innerHTML='جارٍ البحث <span class="variant-searching"><i></i><i></i><i></i></span>';const [base,inc]=$('variantTime').value.split(',').map(Number);const rated=$('variantRated').value==='1';try{const result=await invoke({action:'queue',baseSeconds:base,incrementSeconds:inc,rated});if(result.game){searching=false;clearInterval(queueTimer);$('variantCancel').disabled=true;await loadGame(result.game.id);return}queueTimer=setInterval(async()=>{if(!searching)return;try{const r=await invoke({action:'queue',baseSeconds:base,incrementSeconds:inc,rated});if(r.game){searching=false;clearInterval(queueTimer);$('variantCancel').disabled=true;await loadGame(r.game.id)}}catch(e){console.error(e)}},2500)}catch(e){console.error(e);searching=false;$('variantQueueState').textContent='تعذر بدء البحث.'}finally{$('variantQueue').disabled=searching}}
$('variantQueue').addEventListener('click',queue);$('variantCancel').addEventListener('click',async()=>{searching=false;clearInterval(queueTimer);try{await invoke({action:'cancel_queue'})}catch{}$('variantQueue').disabled=false;$('variantCancel').disabled=true;$('variantQueueState').textContent='تم إلغاء البحث.'});$('variantResign').addEventListener('click',async()=>{if(!current||!confirm('هل تريد الاستسلام؟'))return;try{await invoke({action:'resign',gameId:current.game_id});await loadGame(current.game_id)}catch(e){console.error(e)}});$('variantDraw').addEventListener('click',async()=>{if(!current)return;try{if(current.draw_offered_by&&current.draw_offered_by!==player.id){const accept=confirm('الخصم يعرض التعادل. قبول؟');await invoke({action:'respond_draw',gameId:current.game_id,accept})}else await invoke({action:'offer_draw',gameId:current.game_id});await loadGame(current.game_id)}catch(e){console.error(e)}});
theme();const games=await listGames();const requested=new URLSearchParams(location.search).get('game');await loadGame(requested||(games.find(g=>g.status==='active')?.game_id||''));clockTimer=setInterval(renderMeta,250);poll=setInterval(()=>{if(current?.game_id)void loadGame(current.game_id);else void listGames()},5000);window.addEventListener('pagehide',()=>{clearInterval(clockTimer);clearInterval(poll);clearInterval(queueTimer)});
