import { supabase, rpc, getSessionPlayer, escapeHtml } from '../../v2/platform/api.mjs';
const style=document.createElement('style');style.textContent=`#v3TournamentFormatPanel{margin-top:12px;padding:12px;border:1px solid rgba(216,182,101,.24);border-radius:12px;background:rgba(3,38,40,.32)}.v3-format-head{display:flex;align-items:center;justify-content:space-between;gap:9px;margin-bottom:9px}.v3-format-head strong{color:var(--hero-gold,#d8b665);font-size:14px}.v3-format-badge{padding:4px 8px;border-radius:999px;background:rgba(216,182,101,.12);color:var(--hero-gold-2,#efcf7c);font-size:11px;font-weight:900}.v3-standing{display:grid;grid-template-columns:34px minmax(0,1fr) 60px 42px 42px 42px;gap:4px;padding:7px;border-top:1px solid rgba(216,182,101,.12);font-size:11px;align-items:center}.v3-standing.head{color:#d9c58f;font-weight:900;border-top:0}.v3-arena-btn{margin-top:10px;min-height:38px;padding:0 14px;border:0;border-radius:10px;background:#d8b665;color:#162f30;font-weight:900;cursor:pointer}.v3-arena-note{margin-top:7px;color:#b7c7c2;font-size:11px}@media(max-width:700px){.v3-standing{grid-template-columns:28px minmax(0,1fr) 48px 34px 34px 34px;font-size:9px;padding:6px 3px}}`;document.head.appendChild(style);
let currentId=null,loading=false,lastSignature='';
const formatLabel=v=>v==='arena'?'Arena':v==='swiss'?'Swiss':'إقصاء مباشر';
async function tournamentRow(id){const {data,error}=await supabase.from('tournaments').select('id,format,status,rounds_total,arena_duration_minutes,arena_ends_at').eq('id',id).maybeSingle();if(error)throw error;return data}
async function standings(id){try{return await rpc('v3_tournament_standings',{p_tournament_id:id})||[]}catch(e){console.warn(e);return[]}}
function durationText(row){if(row.format==='arena'&&row.arena_ends_at){const ms=Math.max(0,Date.parse(row.arena_ends_at)-Date.now()),m=Math.ceil(ms/60000);return row.status==='running'?`متبقي نحو ${m} دقيقة`:`مدة Arena: ${row.arena_duration_minutes||60} دقيقة`}if(row.format==='swiss')return `${row.rounds_total||'—'} جولات`;return ''}
async function enterArena(matchId,button){button.disabled=true;button.textContent='تجهيز المباراة…';const poll=async()=>{try{const {data,error}=await supabase.rpc('get_my_tournament_match_access',{p_match_id:matchId});if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(row?.state==='active'&&row.game_id&&row.seat_key&&['w','b'].includes(row.color)){sessionStorage.setItem('shatranj_live_game_id',row.game_id);sessionStorage.setItem('shatranj_live_game_code',row.game_code||'');sessionStorage.setItem('shatranj_live_seat_key',row.seat_key);sessionStorage.setItem('shatranj_live_color',row.color);location.href=`play-v10.html?game=${encodeURIComponent(row.game_id)}`;return}button.textContent=row?.state==='round_break'?'بانتظار الجولة…':'بانتظار الخصم…';setTimeout(poll,1400)}catch(e){console.error(e);button.disabled=false;button.textContent='ابحث عن مباراة'}};poll()}
async function requestArena(button,id){try{button.disabled=true;button.textContent='جارٍ البحث…';const matchId=await rpc('v3_arena_request_pairing',{p_tournament_id:id});if(matchId){await enterArena(matchId,button);return}button.disabled=false;button.textContent='ابحث عن مباراة';const note=document.querySelector('#v3ArenaNote');if(note)note.textContent='أنت في طابور Arena. أعد الضغط بعد لحظات إذا لم يظهر خصم.'}catch(e){console.error(e);button.disabled=false;button.textContent='ابحث عن مباراة';const note=document.querySelector('#v3ArenaNote');if(note)note.textContent='تعذر بدء البحث الآن.'}}
async function render(){if(loading)return;const id=new URLSearchParams(location.search).get('tournament'),host=document.getElementById('tournamentDetailCard');if(!id||!host){currentId=null;document.getElementById('v3TournamentFormatPanel')?.remove();return}loading=true;try{const row=await tournamentRow(id);if(!row)return;currentId=id;const sig=`${id}:${row.format}:${row.status}:${row.arena_ends_at||''}`;let panel=document.getElementById('v3TournamentFormatPanel');if(!panel){panel=document.createElement('section');panel.id='v3TournamentFormatPanel';host.appendChild(panel)}const scores=row.format==='knockout'?[]:await standings(id);const state=await getSessionPlayer();panel.innerHTML=`<div class="v3-format-head"><strong>صيغة البطولة</strong><span class="v3-format-badge">${formatLabel(row.format)}</span></div>${durationText(row)?`<div class="v3-arena-note">${escapeHtml(durationText(row))}</div>`:''}${row.format!=='knockout'?`<div style="margin-top:10px"><div class="v3-standing head"><span>#</span><span>اللاعب</span><span>نقاط</span><span>ف</span><span>ت</span><span>خ</span></div>${scores.map(s=>`<div class="v3-standing"><span>${s.rank_no}</span><span>${escapeHtml(s.player_name)}</span><strong>${s.points}</strong><span>${s.wins}</span><span>${s.draws}</span><span>${s.losses}</span></div>`).join('')||'<div class="v3-arena-note">لم تبدأ النتائج بعد.</div>'}</div>`:''}${row.format==='arena'&&row.status==='running'&&state.player?'<button id="v3ArenaPair" class="v3-arena-btn" type="button">ابحث عن مباراة</button><div id="v3ArenaNote" class="v3-arena-note">ستُعاد للمطابقة بعد كل مباراة حتى نهاية Arena.</div>':''}`;panel.querySelector('#v3ArenaPair')?.addEventListener('click',e=>requestArena(e.currentTarget,id));lastSignature=sig}catch(e){console.warn('تعذر تحميل صيغة البطولة',e)}finally{loading=false}}
const obs=new MutationObserver(()=>queueMicrotask(render));const start=()=>{const host=document.getElementById('tournamentDetailView')||document.body;obs.observe(host,{subtree:true,childList:true});render();setInterval(()=>{if(currentId)render()},10000)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
