import { requirePlayer, rpc, escapeHtml, relativeTime } from '../platform/api.mjs';
const $=id=>document.getElementById(id);const state=await requirePlayer();const me=state.player;let challengeSeconds=600;let chatTarget=null;let refreshTimer=null;
const status=(text,kind='')=>{$('socialStatus').className=`platform-card full ${kind}`;$('socialStatus').textContent=text};
function personCard(p,actions=''){return `<div class="social-person"><div><a class="social-name" href="player.html?id=${encodeURIComponent(p.player_id||p.id)}">${escapeHtml(p.name||p.opponent_name||'لاعب')}</a><div class="social-meta">${escapeHtml(p.country||'')} ${p.city?`· ${escapeHtml(p.city)}`:''} · النقاط ${Number(p.rating??p.opponent_rating??1500)}</div></div><div class="platform-actions">${actions}</div></div>`}
async function searchPlayers(){const q=$('playerSearch').value.trim();if(!q){$('searchResults').innerHTML='<div class="platform-empty">اكتب اسمًا أو مدينة.</div>';return}status('جارٍ البحث…');try{const rows=await rpc('v2_search_players',{p_query:q,p_limit:30});$('searchResults').innerHTML=(rows||[]).map(p=>personCard(p,`<button class="platform-btn" data-friend="${p.id}">صداقة</button><button class="platform-btn primary" data-challenge="${p.id}">تحدي</button><button class="platform-btn danger" data-block="${p.id}">حظر</button>`)).join('')||'<div class="platform-empty">لا توجد نتائج.</div>';status('تم البحث.')}catch(e){console.error(e);status('تعذر البحث.','platform-error')}}
async function loadFriends(){try{const rows=await rpc('v2_list_friends');$('friendsList').innerHTML=(rows||[]).map(p=>personCard(p,`<button class="platform-btn" data-chat="${p.player_id}" data-name="${escapeHtml(p.name)}">رسالة</button><button class="platform-btn primary" data-challenge="${p.player_id}">تحدي</button><button class="platform-btn danger" data-remove-friend="${p.player_id}">إزالة</button>`)).join('')||'<div class="platform-empty">لا يوجد أصدقاء بعد.</div>'}catch(e){console.error(e);$('friendsList').innerHTML='<div class="platform-empty platform-error">تعذر تحميل الأصدقاء.</div>'}}
async function loadRequests(){try{const rows=await rpc('v2_list_friend_requests');$('friendRequests').innerHTML=(rows||[]).map(p=>personCard(p,`<button class="platform-btn primary" data-accept-friend="${p.friendship_id}">قبول</button><button class="platform-btn" data-reject-friend="${p.friendship_id}">رفض</button>`)).join('')||'<div class="platform-empty">لا توجد طلبات.</div>'}catch(e){console.error(e)}}
function challengeLabel(c){const time=c.base_seconds>=3600?`${Math.round(c.base_seconds/3600)} س`:`${Math.round(c.base_seconds/60)} د`;const variant=c.variant==='chess960'?' · Chess960':'';return `${time}${c.increment_seconds?` +${c.increment_seconds}`:''}${variant} · ${c.rated?'نقاط':'ودي'}`}
async function loadChallenges(){try{const rows=await rpc('v2_list_challenges');$('challengeList').innerHTML=(rows||[]).map(c=>{let actions='';if(c.status==='pending'&&c.direction==='incoming')actions=`<button class="platform-btn primary" data-accept-challenge="${c.challenge_id}">قبول</button><button class="platform-btn" data-reject-challenge="${c.challenge_id}">رفض</button>`;else if(c.status==='accepted'&&c.game_id)actions=`<a class="platform-btn primary" href="play-v2.html?game=${encodeURIComponent(c.game_id)}">فتح المباراة</a>`;const dir=c.direction==='incoming'?'تحداك':'تحديته';return `<div class="social-person"><div><strong>${escapeHtml(c.opponent_name)}</strong><div class="social-meta">${dir} · ${challengeLabel(c)} · ${escapeHtml(c.status)}</div></div><div class="platform-actions">${actions}</div></div>`}).join('')||'<div class="platform-empty">لا توجد تحديات.</div>'}catch(e){console.error(e)}}
async function refresh(){await Promise.all([loadFriends(),loadRequests(),loadChallenges()])}
async function actionRpc(name,args,ok){status('جارٍ التنفيذ…');try{const data=await rpc(name,args);status(ok,'platform-ok');await refresh();return data}catch(e){console.error(e);status(e.message?.includes('blocked')?'التواصل محظور بين الحسابين.':'تعذر تنفيذ العملية.','platform-error');throw e}}
async function openChat(id,name){chatTarget=id;$('chatName').textContent=name||'محادثة';$('directMessages').hidden=false;await loadMessages()}
async function loadMessages(){if(!chatTarget)return;try{const rows=await rpc('v2_list_direct_messages',{p_other_player_id:chatTarget,p_limit:150});$('chatMessages').innerHTML=(rows||[]).map(m=>`<div class="chat-message ${m.sender_id===me.id?'mine':'theirs'}"><div>${escapeHtml(m.body)}</div><small class="platform-muted">${relativeTime(m.created_at)}</small></div>`).join('')||'<div class="platform-empty">ابدأ المحادثة.</div>';$('chatMessages').scrollTop=$('chatMessages').scrollHeight}catch(e){console.error(e)}}
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-chat]');if(!b)return;try{if(b.dataset.friend)await actionRpc('v2_send_friend_request',{p_target_player_id:b.dataset.friend},'تم إرسال طلب الصداقة.');else if(b.dataset.acceptFriend)await actionRpc('v2_respond_friend_request',{p_friendship_id:b.dataset.acceptFriend,p_accept:true},'تم قبول الصداقة.');else if(b.dataset.rejectFriend)await actionRpc('v2_respond_friend_request',{p_friendship_id:b.dataset.rejectFriend,p_accept:false},'تم رفض الطلب.');else if(b.dataset.removeFriend)await actionRpc('v2_remove_friend',{p_target_player_id:b.dataset.removeFriend},'تمت إزالة الصديق.');else if(b.dataset.block)await actionRpc('v2_set_block',{p_target_player_id:b.dataset.block,p_block:true},'تم حظر اللاعب.');else if(b.dataset.challenge)await actionRpc('v2_send_challenge',{p_target_player_id:b.dataset.challenge,p_base_seconds:challengeSeconds,p_increment_seconds:0,p_rated:true,p_variant:'standard'},'تم إرسال التحدي.');else if(b.dataset.acceptChallenge){const game=await actionRpc('v2_respond_challenge',{p_challenge_id:b.dataset.acceptChallenge,p_accept:true},'تم قبول التحدي.');if(game)location.href=`play-v2.html?game=${encodeURIComponent(game)}`}else if(b.dataset.rejectChallenge)await actionRpc('v2_respond_challenge',{p_challenge_id:b.dataset.rejectChallenge,p_accept:false},'تم رفض التحدي.');else if(b.dataset.chat)await openChat(b.dataset.chat,b.dataset.name)}catch{}});
$('searchPlayers').addEventListener('click',searchPlayers);$('playerSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchPlayers()});document.querySelectorAll('#challengeTime [data-seconds]').forEach(b=>b.addEventListener('click',()=>{challengeSeconds=Number(b.dataset.seconds);document.querySelectorAll('#challengeTime [data-seconds]').forEach(x=>x.classList.toggle('active',x===b))}));
$('closeChat').addEventListener('click',()=>{$('directMessages').hidden=true;chatTarget=null});$('directMessages').addEventListener('click',e=>{if(e.target===$('directMessages')){$('directMessages').hidden=true;chatTarget=null}});$('chatForm').addEventListener('submit',async e=>{e.preventDefault();const body=$('chatInput').value.trim();if(!body||!chatTarget)return;try{await rpc('v2_send_message',{p_recipient_id:chatTarget,p_body:body});$('chatInput').value='';await loadMessages()}catch(err){console.error(err);status('تعذر إرسال الرسالة.','platform-error')}});
await refresh();refreshTimer=setInterval(()=>{void loadRequests();void loadChallenges();if(chatTarget)void loadMessages()},5000);window.addEventListener('pagehide',()=>clearInterval(refreshTimer));
