import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.SHATRANJ_CONFIG?.supabase||{};const supabase=cfg.enabled&&cfg.url&&cfg.anonKey?createClient(cfg.url,cfg.anonKey):null;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function rpc(name,args={}){const {data,error}=await supabase.rpc(name,args);if(error)throw error;return data}
function iso(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function addTournamentFormatFields(){const modal=$('tournamentModal');if(!modal||$('tournamentFormat'))return;const time=$('tournamentTime')?.closest('.form-group');if(!time)return;const box=document.createElement('div');box.className='form-group';box.innerHTML='<label>صيغة البطولة</label><select id="tournamentFormat" class="field"><option value="knockout">إقصاء مباشر</option><option value="arena">Arena</option><option value="swiss">Swiss</option></select>';time.insertAdjacentElement('afterend',box);const extra=document.createElement('div');extra.id='tournamentFormatExtra';extra.className='form-group';box.insertAdjacentElement('afterend',extra);const sync=()=>{const f=$('tournamentFormat').value;extra.innerHTML=f==='arena'?'<label>مدة Arena بالدقائق</label><input id="tournamentArenaMinutes" class="field" type="number" min="5" max="360" value="60">':f==='swiss'?'<label>عدد جولات Swiss</label><input id="tournamentRounds" class="field" type="number" min="1" max="12" value="5">':'<label>النظام</label><div class="owner-note" style="margin:0">الفائز يتأهل للدور التالي.</div>'};$('tournamentFormat').addEventListener('change',sync);sync()}
async function saveNewV3Tournament(event){const title=$('tournamentModalTitle')?.textContent||'';if(!title.includes('إضافة بطولة'))return;event.preventDefault();event.stopImmediatePropagation();const btn=$('saveTournament');btn.disabled=true;const msg=$('tournamentMessage');if(msg)msg.textContent='جارٍ الحفظ…';try{const scope=$('tournamentScope').value,mode=$('tournamentCapacityMode').value,max=mode==='fixed'?Number($('tournamentMax').value):null,format=$('tournamentFormat')?.value||'knockout';if(mode==='fixed'&&(!Number.isInteger(max)||max<2))throw new Error('حدد عدد المشاركين.');await rpc('admin_create_tournament_v3',{p_name:$('tournamentName').value.trim(),p_scope_type:scope,p_country:scope==='global'?null:$('tournamentCountry').value,p_city:scope==='city'?$('tournamentCity').value:null,p_time_control:$('tournamentTime').value,p_starts_at:iso($('tournamentStarts').value),p_registration_opens_at:iso($('tournamentRegOpen').value),p_registration_closes_at:iso($('tournamentRegClose').value),p_max_players:mode==='open'?null:max,p_status:$('tournamentStatus').value,p_format:format,p_rounds_total:format==='swiss'?Number($('tournamentRounds')?.value||5):null,p_arena_duration_minutes:format==='arena'?Number($('tournamentArenaMinutes')?.value||60):null});$('tournamentModal').hidden=true;$('refreshBtn')?.click()}catch(e){console.error(e);if(msg)msg.textContent=e.message||'تعذر حفظ البطولة.'}finally{btn.disabled=false}}
function targetLabel(t){return({player:'لاعب',message:'رسالة',club:'نادي',game:'مباراة',variant_game:'Chess960',daily_game:'يومية'})[t]||t}
async function loadModeration(){const body=$('v3ModerationBody');if(!body||!supabase)return;try{const rows=await rpc('admin_v3_list_reports',{p_status:'open'});body.innerHTML=(rows||[]).map(r=>`<tr><td>${esc(targetLabel(r.target_type))}</td><td>${esc(r.reporter_name)}</td><td>${esc(r.reported_name||'—')}</td><td>${esc(r.reason)}<div style="font-size:10px;color:var(--muted);margin-top:3px">${esc(r.details||'')}</div></td><td>${new Date(r.created_at).toLocaleString('ar-SA')}</td><td><div class="table-actions"><button class="action-btn" data-v3-action="dismiss" data-report="${r.id}">إغلاق</button>${r.reported_player_id?`<button class="action-btn" data-v3-action="warn" data-report="${r.id}">تنبيه</button><button class="action-btn danger" data-v3-action="suspend" data-report="${r.id}">تعليق</button>`:''}${r.target_type==='message'?`<button class="action-btn danger" data-v3-action="remove_content" data-report="${r.id}">حذف الرسالة</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد بلاغات V3 مفتوحة.</td></tr>'}catch(e){console.error(e);body.innerHTML='<tr><td colspan="6" class="empty">تعذر تحميل البلاغات الجديدة.</td></tr>'}}
async function moderate(button){const action=button.dataset.v3Action,id=button.dataset.report;if(!action||!id)return;let reason='';if(action!=='dismiss'){reason=prompt('سبب الإجراء الإداري:','')||'';if(reason.trim().length<3)return}if(!confirm('تأكيد الإجراء؟'))return;button.disabled=true;try{await rpc('admin_v3_resolve_report',{p_report_id:id,p_action:action,p_reason:reason.trim()});await loadModeration();$('refreshBtn')?.click()}catch(e){console.error(e);alert('تعذر تنفيذ الإجراء.')}finally{button.disabled=false}}
function addModerationPanel(){const host=$('reportsView');if(!host||$('v3ModerationPanel'))return;const section=document.createElement('div');section.id='v3ModerationPanel';section.innerHTML='<h3 class="section-title">بلاغات المجتمع وPhase 3</h3><div class="table-wrap"><table><thead><tr><th>الهدف</th><th>المبلّغ</th><th>المبلّغ عنه</th><th>السبب</th><th>الوقت</th><th>الإجراء</th></tr></thead><tbody id="v3ModerationBody"><tr><td colspan="6" class="empty">جارٍ التحميل…</td></tr></tbody></table></div>';host.appendChild(section);section.addEventListener('click',e=>{const b=e.target.closest('[data-v3-action]');if(b)moderate(b)});loadModeration()}
function start(){if(!$('adminApp')||$('adminApp').hidden){setTimeout(start,180);return}addTournamentFormatFields();addModerationPanel();$('saveTournament')?.addEventListener('click',saveNewV3Tournament,true);$('refreshBtn')?.addEventListener('click',loadModeration);new MutationObserver(()=>{if(!$('tournamentModal')?.hidden){addTournamentFormatFields();if(($('tournamentModalTitle')?.textContent||'').includes('إضافة')){$('tournamentFormat').value='knockout';$('tournamentFormat').dispatchEvent(new Event('change'))}}}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['hidden']});setInterval(()=>{if($('reportsView')?.classList.contains('active'))loadModeration()},12000)}
start();
