import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { StockfishAnalyzer, scoreToCp } from './engine.mjs';
import { loadBoardPreferences } from '../board/preferences.mjs';
import { getBoardTheme } from '../board/themes.mjs';

const $=id=>document.getElementById(id);const board=$('analysisBoard');
let chess=new Chess(),selected=null,orientation='w';const engine=new StockfishAnalyzer();let busy=false;
function applyTheme(){const t=getBoardTheme(loadBoardPreferences().theme);board.style.setProperty('--board-light',t.light);board.style.setProperty('--board-dark',t.dark)}
function pieces(fen){const out=new Map();fen.split(' ')[0].split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=+c;continue}out.set(`${String.fromCharCode(97+f)}${8-ri}`,{color:c===c.toUpperCase()?'w':'b',type:c.toLowerCase()});f++}});return out}
function order(){const files=orientation==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'];const ranks=orientation==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function render(){const pos=pieces(chess.fen());const frag=document.createDocumentFragment();for(const name of order()){const file=name.charCodeAt(0)-97,rank=+name[1],sq=document.createElement('button');sq.type='button';sq.dataset.square=name;sq.className=`analysis-square ${(file+rank)%2===1?'light':'dark'}${selected===name?' selected':''}`;const p=pos.get(name);if(p){const img=document.createElement('img');img.className='analysis-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);highlight();$('fenInput').value=chess.fen()}
function highlight(){board.querySelectorAll('.target').forEach(x=>x.classList.remove('target'));if(!selected)return;for(const m of chess.moves({square:selected,verbose:true}))board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}
board.addEventListener('click',e=>{if(busy)return;const sq=e.target.closest('.analysis-square');if(!sq)return;const name=sq.dataset.square,p=chess.get(name);if(!selected){if(p?.color===chess.turn()){selected=name;render()}return}if(name===selected){selected=null;render();return}if(p?.color===chess.turn()){selected=name;render();return}try{const move=chess.move({from:selected,to:name,promotion:'q'});selected=null;if(move){render();void analyzeCurrent()}else render()}catch{selected=null;render()}});
function formatEval(result){if(Number.isFinite(result?.mate))return result.mate>0?`M${result.mate}`:`-M${Math.abs(result.mate)}`;return ((Number(result?.cp)||0)/100).toFixed(2)}
export async function analyzeFen(fen,depth=16){return engine.analyzeFen(fen,depth)}
async function analyzeCurrent(){if(busy)return;busy=true;$('analysisStatus').textContent='Stockfish يحلل…';try{const r=await analyzeFen(chess.fen(),+$('analysisDepth').value);$('engineEval').textContent=formatEval(r);$('engineBest').textContent=`أفضل نقلة ${r.bestMove||'—'} · عمق ${r.depth||'—'}`;$('engineLine').textContent=r.pv||'لا يوجد خط رئيسي';$('analysisStatus').textContent=''}catch(e){$('analysisStatus').textContent=e.message||'تعذر التحليل'}finally{busy=false}}
export function classifyMove(loss){if(loss<=20)return {key:'best',label:'الأفضل'};if(loss<=50)return {key:'excellent',label:'ممتاز'};if(loss<=100)return {key:'good',label:'جيد'};if(loss<=180)return {key:'inaccuracy',label:'عدم دقة'};if(loss<=350)return {key:'mistake',label:'خطأ'};return {key:'blunder',label:'خطأ فادح'}}
export function accuracy(avgLoss){return Math.max(0,Math.min(100,Math.round(100*Math.exp(-Math.max(0,avgLoss)/250))))}
function loadFen(){try{chess=new Chess($('fenInput').value.trim());selected=null;render();$('analysisStatus').textContent='تم تحميل الوضع.'}catch(e){$('analysisStatus').textContent='FEN غير صالح.'}}
function loadPgnText(){try{const c=new Chess();c.loadPgn($('pgnInput').value.trim());chess=c;selected=null;render();$('analysisStatus').textContent=`تم تحميل ${c.history().length} نقلة.`;return c}catch(e){$('analysisStatus').textContent='PGN غير صالح.';return null}}
async function reviewGame(){let parsed;try{parsed=new Chess();parsed.loadPgn($('pgnInput').value.trim())}catch{$('analysisStatus').textContent='PGN غير صالح.';return}const moves=parsed.history({verbose:true}).slice(0,60);if(!moves.length){$('analysisStatus').textContent='لا توجد نقلات للمراجعة.';return}busy=true;$('runReview').disabled=true;$('reviewResults').innerHTML='';const positions=[moves[0].before,...moves.map(m=>m.after)];const evals=[];try{for(let i=0;i<positions.length;i++){$('analysisStatus').textContent=`تحليل الموضع ${i+1} من ${positions.length}…`;const r=await analyzeFen(positions[i],10);evals.push(scoreToCp(r))}let total=0;const rows=moves.map((m,i)=>{const before=evals[i],actual=-evals[i+1],loss=Math.max(0,before-actual),kind=classifyMove(loss);total+=loss;return `<div class="review-move"><span>${Math.floor(i/2)+1}${i%2?'…':'.'}</span><strong>${m.san}</strong><span class="review-tag ${kind.key}">${kind.label}</span><span>${Math.round(loss)}cp</span></div>`}).join('');const avg=total/moves.length,acc=accuracy(avg);$('reviewSummary').innerHTML=`الدقة التقديرية <strong>${acc}%</strong> · متوسط فقدان ${Math.round(avg)} سنتيبيدق · تمت مراجعة ${moves.length} نصف نقلة.`;$('reviewResults').innerHTML=rows;$('analysisStatus').textContent='اكتملت المراجعة.'}catch(e){console.error(e);$('analysisStatus').textContent=e.message||'تعذرت المراجعة.'}finally{busy=false;$('runReview').disabled=false}}
$('runAnalysis').addEventListener('click',analyzeCurrent);$('loadFen').addEventListener('click',loadFen);$('loadPgn').addEventListener('click',loadPgnText);$('runReview').addEventListener('click',reviewGame);$('resetBoard').addEventListener('click',()=>{chess=new Chess();selected=null;render()});$('flipBoard').addEventListener('click',()=>{orientation=orientation==='w'?'b':'w';render()});$('copyFen').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(chess.fen());$('analysisStatus').textContent='تم نسخ FEN.'}catch{}});window.addEventListener('pagehide',()=>engine.destroy());
applyTheme();render();
