import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { StockfishAnalyzer, scoreToCp } from './engine.mjs';
import { loadBoardPreferences } from '../board/preferences.mjs';
import { getBoardTheme } from '../board/themes.mjs';
import { getSessionPlayer, rpc } from '../platform/api.mjs';

const $=id=>document.getElementById(id);const board=$('analysisBoard');
let chess=new Chess(),selected=null,orientation='w';const engine=new StockfishAnalyzer();let busy=false;
function applyTheme(){const t=getBoardTheme(loadBoardPreferences().theme);board.style.setProperty('--board-light',t.light);board.style.setProperty('--board-dark',t.dark)}
function pieces(fen){const out=new Map();fen.split(' ')[0].split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=+c;continue}out.set(`${String.fromCharCode(97+f)}${8-ri}`,{color:c===c.toUpperCase()?'w':'b',type:c.toLowerCase()});f++}});return out}
function order(){const files=orientation==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'];const ranks=orientation==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function render(){const pos=pieces(chess.fen());const frag=document.createDocumentFragment();for(const name of order()){const file=name.charCodeAt(0)-97,rank=+name[1],sq=document.createElement('button');sq.type='button';sq.dataset.square=name;sq.className=`analysis-square ${(file+rank)%2===1?'light':'dark'}${selected===name?' selected':''}`;const p=pos.get(name);if(p){const img=document.createElement('img');img.className='analysis-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);highlight();$('fenInput').value=chess.fen()}
function highlight(){board.querySelectorAll('.target').forEach(x=>x.classList.remove('target'));if(!selected)return;for(const m of chess.moves({square:selected,verbose:true}))board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}
board.addEventListener('click',e=>{if(busy)return;const sq=e.target.closest('.analysis-square');if(!sq)return;const name=sq.dataset.square,p=chess.get(name);if(!selected){if(p?.color===chess.turn()){selected=name;render()}return}if(name===selected){selected=null;render();return}if(p?.color===chess.turn()){selected=name;render();return}try{const move=chess.move({from:selected,to:name,promotion:'q'});selected=null;if(move){render();void analyzeCurrent()}else render()}catch{selected=null;render()}});
function formatEval(result){if(Number.isFinite(result?.mate))return result.mate>0?`M${result.mate}`:`-M${Math.abs(result.mate)}`;return ((Number(result?.cp)||0)/100).toFixed(2)}
function cpText(value){if(Math.abs(value)>90000)return value>0?'مات للأبيض':'مات للأسود';return `${(value/100).toFixed(2)}`}
export async function analyzeFen(fen,depth=16){return engine.analyzeFen(fen,depth)}
async function analyzeCurrent(){if(busy)return;busy=true;$('analysisStatus').textContent='Stockfish يحلل…';try{const r=await analyzeFen(chess.fen(),+$('analysisDepth').value);$('engineEval').textContent=formatEval(r);$('engineBest').textContent=`أفضل نقلة ${r.bestMove||'—'} · عمق ${r.depth||'—'}`;$('engineLine').textContent=r.pv||'لا يوجد خط رئيسي';$('analysisStatus').textContent=''}catch(e){$('analysisStatus').textContent=e.message||'تعذر التحليل'}finally{busy=false}}
export function classifyMove(loss){if(loss<=20)return {key:'best',label:'الأفضل'};if(loss<=50)return {key:'excellent',label:'ممتاز'};if(loss<=100)return {key:'good',label:'جيد'};if(loss<=180)return {key:'inaccuracy',label:'عدم دقة'};if(loss<=350)return {key:'mistake',label:'خطأ'};return {key:'blunder',label:'خطأ فادح'}}
export function accuracy(avgLoss){return Math.max(0,Math.min(100,Math.round(100*Math.exp(-Math.max(0,avgLoss)/250))))}
function loadFen(){try{chess=new Chess($('fenInput').value.trim());selected=null;render();$('analysisStatus').textContent='تم تحميل الوضع.'}catch(e){$('analysisStatus').textContent='FEN غير صالح.'}}
function loadPgnText(){try{const c=new Chess();c.loadPgn($('pgnInput').value.trim());chess=c;selected=null;render();$('analysisStatus').textContent=`تم تحميل ${c.history().length} نقلة.`;return c}catch(e){$('analysisStatus').textContent='PGN غير صالح.';return null}}
function moveUci(m){return `${m.from}${m.to}${m.promotion||''}`}
function avg(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0}
function phaseForFen(fen,ply){const material=fen.split(' ')[0].replace(/[1-8\/]/g,'').replace(/[kKpP]/g,'').length;if(ply<=20)return 'opening';if(material<=6)return 'endgame';return 'middlegame'}
function sourceContext(){const q=new URLSearchParams(location.search),source=q.get('source'),game=q.get('game');return source&&game?{source,game}:null}
async function persistReview(payload){const ctx=sourceContext();if(!ctx)return null;try{const state=await getSessionPlayer();if(!state.player)return null;return await rpc('v3_save_game_review',{p_source_type:ctx.source,p_source_id:ctx.game,p_accuracy_white:payload.accuracyWhite,p_accuracy_black:payload.accuracyBlack,p_summary:payload.summary,p_moves:payload.moves})}catch(e){console.warn('تعذر حفظ Game Review',e);return null}}
async function reviewGame(){let parsed;try{parsed=new Chess();parsed.loadPgn($('pgnInput').value.trim())}catch{$('analysisStatus').textContent='PGN غير صالح.';return}const moves=parsed.history({verbose:true}).slice(0,80);if(!moves.length){$('analysisStatus').textContent='لا توجد نقلات للمراجعة.';return}busy=true;$('runReview').disabled=true;$('reviewResults').innerHTML='';const positions=[moves[0].before,...moves.map(m=>m.after)],engineRows=[];try{for(let i=0;i<positions.length;i++){$('analysisStatus').textContent=`تحليل الموضع ${i+1} من ${positions.length}…`;engineRows.push(await analyzeFen(positions[i],11))}const whiteLoss=[],blackLoss=[],phaseStats={opening:{loss:0,count:0},middlegame:{loss:0,count:0},endgame:{loss:0,count:0}};let critical=0;const detail=moves.map((m,i)=>{const before=scoreToCp(engineRows[i]),actual=-scoreToCp(engineRows[i+1]),loss=Math.max(0,before-actual);const legalCount=new Chess(m.before).moves().length;const forced=legalCount<=1;const kind=forced?{key:'forced',label:'إجباري'}:classifyMove(loss);const isCritical=loss>=100||Math.abs(before-actual)>=150;if(isCritical)critical++;(m.color==='w'?whiteLoss:blackLoss).push(loss);const phase=phaseForFen(m.before,i+1);phaseStats[phase].loss+=loss;phaseStats[phase].count++;return {ply:i+1,san:m.san,playedMove:moveUci(m),bestMove:engineRows[i].bestMove||null,evalBefore:before,evalAfter:actual,lossCp:Math.round(loss),classification:kind.key,label:kind.label,pv:engineRows[i].pv||'',isCritical,phase}});const accuracyWhite=accuracy(avg(whiteLoss)),accuracyBlack=accuracy(avg(blackLoss));const totalLoss=[...whiteLoss,...blackLoss],averageLoss=avg(totalLoss);const summary={accuracyWhite,accuracyBlack,averageLossCp:Math.round(averageLoss),criticalCount:critical,reviewedPlies:detail.length,phases:Object.fromEntries(Object.entries(phaseStats).map(([k,v])=>[k,{averageLossCp:v.count?Math.round(v.loss/v.count):0,count:v.count}]))};$('reviewSummary').innerHTML=`دقة الأبيض <strong>${accuracyWhite}%</strong> · دقة الأسود <strong>${accuracyBlack}%</strong> · ${critical} لحظات حرجة · متوسط الفقد ${Math.round(averageLoss)}cp.`;$('reviewResults').innerHTML=detail.map((r,i)=>`<div class="review-move${r.isCritical?' critical':''}"><span>${Math.floor(i/2)+1}${i%2?'…':'.'}</span><strong>${r.san}</strong><span class="review-tag ${r.classification}">${r.label}</span><span>${r.lossCp}cp</span><small style="grid-column:1/-1;color:var(--p-muted)">التقييم ${cpText(r.evalBefore)} ← ${cpText(r.evalAfter)} · الأفضل ${r.bestMove||'—'}${r.isCritical?' · لحظة حرجة':''}${r.pv?` · ${r.pv.split(/\s+/).slice(0,6).join(' ')}`:''}</small></div>`).join('');const saved=await persistReview({accuracyWhite,accuracyBlack,summary,moves:detail});$('analysisStatus').textContent=saved?'اكتملت المراجعة وحُفظت في حسابك.':'اكتملت المراجعة.'}catch(e){console.error(e);$('analysisStatus').textContent=e.message||'تعذرت المراجعة.'}finally{busy=false;$('runReview').disabled=false}}
$('runAnalysis').addEventListener('click',analyzeCurrent);$('loadFen').addEventListener('click',loadFen);$('loadPgn').addEventListener('click',loadPgnText);$('runReview').addEventListener('click',reviewGame);$('resetBoard').addEventListener('click',()=>{chess=new Chess();selected=null;render()});$('flipBoard').addEventListener('click',()=>{orientation=orientation==='w'?'b':'w';render()});$('copyFen').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(chess.fen());$('analysisStatus').textContent='تم نسخ FEN.'}catch{}});window.addEventListener('pagehide',()=>engine.destroy());
applyTheme();render();
