import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { requirePlayer, rpc, supabase, escapeHtml } from '../platform/api.mjs';
import { loadBoardPreferences } from '../board/preferences.mjs';
import { getBoardTheme } from '../board/themes.mjs';
const $=id=>document.getElementById(id);const {player}=await requirePlayer();const board=$('dailyBoard');let current=null,chess=null,selected=null,timer=null,poll=null;
function theme(){const t=getBoardTheme(loadBoardPreferences().theme);board.style.setProperty('--board-light',t.light);board.style.setProperty('--board-dark',t.dark)}
function parse(fen){const m=new Map();fen.split(' ')[0].split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=Number(c);continue}m.set(`${String.fromCharCode(97+f)}${8-ri}`,{color:c===c.toUpperCase()?'w':'b',type:c.toLowerCase()});f++}});return m}
function squares(){const color=current?.my_color||'w',files=color==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=color==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function canMove(){return current?.status==='active'&&current.turn===current.my_color&&Date.parse(current.move_due_at)>Date.now()}
function renderBoard(){if(!chess)return;const pos=parse(chess.fen()),frag=document.createDocumentFragment();for(const name of squares()){const file=name.charCodeAt(0)-97,rank=Number(name[1]),sq=document.createElement('button');sq.type='button';sq.dataset.square=name;sq.className=`daily-square ${(file+rank)%2===1?'light':'dark'}${selected===name?' selected':''}`;const p=pos.get(name);if(p){const img=document.createElement('img');img.className='daily-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);if(selected&&canMove())for(const m of chess.moves({square:selected,verbose:true}))board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}
function dueText(){if(!current||current.status!=='active')return '—';const ms=Math.max(0,Date.parse(current.move_due_at)-Date.now()),d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return `${d}ي ${h}س ${m}د`}
function renderMeta(){if(!current){$('dailyGameTitle').textContent='لا توجد مباراة مفتوحة';$('dailyTurn').textContent='اختر مباراة أو ابدأ واحدة جديدة';$('dailyDue').textContent='—';$('dailyStatus').textContent='—';$('dailyResign').disabled=true;return}const opponent=current.my_color==='w'?current.black_name:current.white_name;$('dailyGameTitle').textContent=`ضد ${opponent} · ${current.days_per_move} يوم/نقلة`;$('dailyTurn').textContent=current.status==='active'?(current.turn===current.my_color?'دورك الآن':'بانتظار الخصم'):(current.result==='1/2-1/2'?'تعادل':`انتهت ${current.result||''}`);$('dailyDue').textContent=dueText();$('dailyStatus').textContent=current.status==='active'?`النقلة ${current.ply+1} · ${current.rated?'نقاط':'ودية'}`:`المباراة ${current.status}`;$('dailyResign').disabled=current.status!=='active'}
async function listGames(){try{const rows=await rpc('v2_list_daily_games');$('dailyGames').innerHTML=(rows||[]).map(g=>{const opp=g.my_color==='w'?g.black_name:g.white_name;return `<a class="daily-game-row ${current?.game_id===g.game_id?'active':''}" href="daily.html?game=${encodeURIComponent(g.game_id)}"><span><strong>${escapeHtml(opp)}</strong><div class="platform-muted" style="font-size:10px">${g.status==='active'?(g.turn===g.my_color?'دورك':'دور الخصم'):`${g.result||g.status}`}</div></span><span class="platform-badge">${g.days_per_move}ي</span></a>`}).join('')||'<div class="platform-empty">لا توجد مباريات يومية.</div>';return rows||[]}catch(e){console.error(e);return[]}}
async function loadGame(id){if(!id){current=null;chess=new Chess();renderBoard();renderMeta();return}try{const rows=await rpc('v2_get_daily_game',{p_game_id:id});const game=Array.isArray(rows)?rows[0]:rows;if(!game)throw new Error('not found');current=game;chess=new Chess(current.fen);selected=null;renderBoard();renderMeta();await listGames()}catch(e){console.error(e);$('dailyStatus').textContent='تعذر تحميل المباراة.'}}
async function invoke(body){const {data,error}=await supabase.functions.invoke('daily-game-v2',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
async function move(from,to){if(!current||!canMove())return;let promotion=null;const piece=chess.get(from);if(piece?.type==='p'&&(to.endsWith('1')||to.endsWith('8')))promotion='q';try{board.style.pointerEvents='none';await invoke({action:'move',gameId:current.game_id,expectedPly:current.ply,from,to,promotion});await loadGame(current.game_id)}catch(e){console.error(e);$('dailyStatus').textContent=e.message?.includes('Illegal')?'نقلة غير قانونية.':'تعذر تنفيذ النقلة.';await loadGame(current.game_id)}finally{board.style.pointerEvents=''}}
board.addEventListener('click',async e=>{if(!chess||!canMove())return;const sq=e.target.closest('.daily-square');if(!sq)return;const name=sq.dataset.square,p=chess.get(name);if(!selected){if(p?.color===current.my_color){selected=name;renderBoard()}return}if(name===selected){selected=null;renderBoard();return}if(p?.color===current.my_color){selected=name;renderBoard();return}const from=selected;selected=null;await move(from,name)});
async function search(){const q=$('dailyPlayerSearch').value.trim();if(!q)return;try{const rows=await rpc('v2_search_players',{p_query:q,p_limit:20});$('dailySearchResults').innerHTML=(rows||[]).map(p=>`<div class="platform-row"><span><strong>${escapeHtml(p.name)}</strong><small class="platform-muted"> · ${Number(p.rating||1500)}</small></span><button class="platform-btn primary" data-daily-player="${p.id}">ابدأ</button></div>`).join('')||'<div class="platform-empty">لا توجد نتائج.</div>'}catch(e){console.error(e)}}
$('dailySearchButton').addEventListener('click',search);$('dailyPlayerSearch').addEventListener('keydown',e=>{if(e.key==='Enter')search()});$('dailySearchResults').addEventListener('click',async e=>{const b=e.target.closest('[data-daily-player]');if(!b)return;try{b.disabled=true;const id=await rpc('v2_create_daily_game',{p_target_player_id:b.dataset.dailyPlayer,p_days_per_move:Number($('daysPerMove').value),p_rated:true});location.href=`daily.html?game=${encodeURIComponent(id)}`}catch(err){console.error(err);$('dailyStatus').textContent='تعذر إنشاء المباراة.'}finally{b.disabled=false}});$('dailyResign').addEventListener('click',async()=>{if(!current||!confirm('هل تريد الاستسلام؟'))return;try{await invoke({action:'resign',gameId:current.game_id});await loadGame(current.game_id)}catch(e){console.error(e)}});$('refreshDaily').addEventListener('click',()=>current?loadGame(current.game_id):listGames());
theme();const games=await listGames();const requested=new URLSearchParams(location.search).get('game');await loadGame(requested||(games.find(g=>g.status==='active')?.game_id||''));timer=setInterval(()=>{renderMeta();if(current?.status==='active'&&Date.parse(current.move_due_at)<=Date.now())void invoke({action:'timeout',gameId:current.game_id}).then(()=>loadGame(current.game_id)).catch(()=>{})},30000);poll=setInterval(()=>{if(current?.game_id)void loadGame(current.game_id);else void listGames()},12000);window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(poll)});
