import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { supabase, getSessionPlayer, rpc } from '../platform/api.mjs';
import { loadBoardPreferences } from '../board/preferences.mjs';
import { getBoardTheme } from '../board/themes.mjs';

const $=id=>document.getElementById(id);
const board=$('puzzleBoard'), statusEl=$('puzzleStatus'), titleEl=$('puzzleTitle'), ratingEl=$('puzzleRating'), heartsEl=$('puzzleHearts'), rushEl=$('puzzleRush');
const modeButtons=[...document.querySelectorAll('[data-mode]')];
let mode='rated', puzzle=null, chess=null, startFen='', selected=null, userColor='w', mistakes=0, hearts=5, player=null, solved=false;
let rush={active:false,endsAt:0,score:0,misses:0,timer:null};

function themeBoard(){const pref=loadBoardPreferences();const theme=getBoardTheme(pref.theme);board.style.setProperty('--board-light',theme.light);board.style.setProperty('--board-dark',theme.dark)}
function parseFenPieces(fen){const [placement]=fen.split(/\s+/);const out=new Map();placement.split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=Number(c);continue}const color=c===c.toUpperCase()?'w':'b';out.set(`${String.fromCharCode(97+f)}${8-ri}`,{color,type:c.toLowerCase()});f++}});return out}
function squareOrder(){const files=userColor==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'];const ranks=userColor==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function render(){if(!chess)return;const pieces=parseFenPieces(chess.fen());const frag=document.createDocumentFragment();for(const sqName of squareOrder()){const file=sqName.charCodeAt(0)-97,rank=Number(sqName[1]);const sq=document.createElement('button');sq.type='button';sq.className=`puzzle-square ${(file+rank)%2===1?'light':'dark'}${selected===sqName?' selected':''}`;sq.dataset.square=sqName;const p=pieces.get(sqName);if(p){const img=document.createElement('img');img.className='puzzle-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);highlightLegal()}
function highlightLegal(){board.querySelectorAll('.target').forEach(x=>x.classList.remove('target'));if(!selected||!chess)return;for(const m of chess.moves({square:selected,verbose:true})){board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}}
function uci(move){return `${move.from}${move.to}${move.promotion||''}`}
function setStatus(text,cls=''){statusEl.className=`puzzle-status ${cls}`;statusEl.textContent=text}
function first(value){return Array.isArray(value)?value[0]||null:value||null}
function applyUci(moveUci){if(!moveUci||!chess)return null;return chess.move({from:moveUci.slice(0,2),to:moveUci.slice(2,4),promotion:moveUci[4]||'q'})}
async function getStats(){try{const state=await getSessionPlayer();player=state.player;if(!player){ratingEl.textContent='زائر';return}const {data}=await supabase.from('v2_player_stats').select('puzzle_rating,daily_puzzle_streak').eq('player_id',player.id).maybeSingle();ratingEl.textContent=String(data?.puzzle_rating??1200)}catch{ratingEl.textContent='—'}}
async function fetchPuzzle(){return first(await rpc('v3_start_puzzle_session',{p_mode:mode,p_theme:mode==='custom'?($('customTheme').value||null):null}))}
export async function loadPuzzle(){selected=null;mistakes=0;solved=false;board.classList.add('busy');setStatus('جارٍ تحميل اللغز…','platform-muted');try{puzzle=await fetchPuzzle();if(!puzzle){setStatus('لا توجد ألغاز متاحة لهذا الوضع حاليًا.','platform-error');return}startFen=puzzle.fen;chess=new Chess(startFen);userColor=chess.turn();titleEl.textContent=`${puzzle.title} · ${puzzle.rating}`;setStatus(userColor==='w'?'دور الأبيض: ابحث عن أفضل نقلة.':'دور الأسود: ابحث عن أفضل نقلة.');render()}catch(e){console.error(e);setStatus('لا توجد ألغاز متاحة لهذا الوضع حاليًا.','platform-error')}finally{board.classList.remove('busy')}}
export async function finishPuzzle(success,row={}){if(solved)return;solved=true;if(row?.ratingAfter!=null)ratingEl.textContent=String(row.ratingAfter);if(rush.active){if(success)rush.score++;else rush.misses++;rushEl.textContent=`${rush.score} / ${rush.misses}`;if(rush.misses>=3){stopRush('انتهى Rush بعد 3 أخطاء.');return}setTimeout(loadPuzzle,450);return}if(success){setStatus(`صحيح!${row?.delta?` ${row.delta>0?'+':''}${row.delta} نقطة ألغاز`:''}`,'platform-ok')}else setStatus('ليست النقلة المطلوبة. حاول لغزًا جديدًا.','platform-error')}
async function validateMove(moveUci){return await rpc('v3_submit_puzzle_session_move',{p_session_id:puzzle.session_id,p_session_secret:puzzle.session_secret,p_move_uci:moveUci})}
async function recoverSession(){if(!puzzle)return loadPuzzle();try{const ok=await rpc('v3_restart_puzzle_session',{p_session_id:puzzle.session_id,p_session_secret:puzzle.session_secret});if(!ok)return loadPuzzle();chess=new Chess(startFen);selected=null;mistakes=0;solved=false;if(mode==='daily'){hearts=5;heartsEl.textContent='5'}render();setStatus('أعيدت مزامنة اللغز. حاول من البداية.','platform-muted')}catch{return loadPuzzle()}}
async function tryMove(from,to){if(solved||!puzzle||chess.turn()!==userColor)return;let candidate;try{candidate=chess.move({from,to,promotion:'q'})}catch{return}if(!candidate)return;board.classList.add('busy');try{const result=await validateMove(uci(candidate));mistakes=Number(result?.mistakes||0);if(!result?.correct){chess.undo();selected=null;render();if(mode==='daily'){hearts=Math.max(0,5-mistakes);heartsEl.textContent=String(hearts);if(result.completed)await finishPuzzle(false,result);else setStatus(`ليست الأفضل. بقي ${hearts} قلوب.`,'platform-error')}else await finishPuzzle(false,result);return}selected=null;render();if(result.replyMove){await new Promise(r=>setTimeout(r,260));const reply=applyUci(String(result.replyMove));if(!reply)throw new Error('invalid_server_reply');render()}if(result.completed){await finishPuzzle(Boolean(result.success),result);return}setStatus('صحيح، تابع وابحث عن أفضل نقلة.','platform-ok')}catch(e){console.error(e);await recoverSession()}finally{board.classList.remove('busy')}}
board.addEventListener('click',async e=>{const sq=e.target.closest('.puzzle-square');if(!sq||!chess||solved)return;const name=sq.dataset.square;const piece=chess.get(name);if(!selected){if(piece?.color===userColor&&chess.turn()===userColor){selected=name;render()}return}if(name===selected){selected=null;render();return}if(piece?.color===userColor){selected=name;render();return}const from=selected;selected=null;await tryMove(from,name)});
function stopRush(message){rush.active=false;if(rush.timer)clearInterval(rush.timer);rush.timer=null;setStatus(`${message} النتيجة ${rush.score}.`,'platform-ok')}
function startRush(){if(rush.timer)clearInterval(rush.timer);rush={active:true,endsAt:Date.now()+180000,score:0,misses:0,timer:null};const tick=()=>{const left=Math.max(0,rush.endsAt-Date.now());rushEl.textContent=`${Math.ceil(left/1000)}ث · ${rush.score}`;if(left<=0)stopRush('انتهى الوقت.');};rush.timer=setInterval(tick,250);tick();loadPuzzle()}
function setMode(next){mode=next;modeButtons.forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('customThemeWrap').hidden=mode!=='custom';hearts=5;heartsEl.textContent=mode==='daily'?'5':'—';if(rush.timer)clearInterval(rush.timer);rush.active=false;rushEl.textContent=mode==='rush'?'180ث':'—';if(mode==='rush')startRush();else loadPuzzle()}
modeButtons.forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('nextPuzzle').addEventListener('click',()=>mode==='rush'?startRush():loadPuzzle());$('resetPuzzle').addEventListener('click',async()=>{if(!puzzle)return;if(solved){await loadPuzzle();return}try{const ok=await rpc('v3_restart_puzzle_session',{p_session_id:puzzle.session_id,p_session_secret:puzzle.session_secret});if(!ok){await loadPuzzle();return}chess=new Chess(startFen);selected=null;mistakes=0;if(mode==='daily'){hearts=5;heartsEl.textContent='5'}render();setStatus('أعيد الوضع. ابحث عن أفضل نقلة.')}catch(e){console.error(e);setStatus('تعذر إعادة اللغز.','platform-error')}});$('customTheme').addEventListener('change',()=>{if(mode==='custom')loadPuzzle()});
themeBoard();await getStats();await loadPuzzle();
