import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { requirePlayer, rpc } from '../../v2/platform/api.mjs';
import { loadBoardPreferences } from '../../v2/board/preferences.mjs';
import { getBoardTheme } from '../../v2/board/themes.mjs';
const $=id=>document.getElementById(id);const {player}=await requirePlayer();const board=$('battleBoard');let battleId=null,state=null,chess=null,userColor='w',selected=null,searchTimer=null,pollTimer=null,clockTimer=null,searching=false;
function theme(){const t=getBoardTheme(loadBoardPreferences().theme);board.style.setProperty('--board-light',t.light);board.style.setProperty('--board-dark',t.dark)}
function parse(fen){const out=new Map();fen.split(' ')[0].split('/').forEach((row,ri)=>{let f=0;for(const c of row){if(/\d/.test(c)){f+=Number(c);continue}out.set(`${String.fromCharCode(97+f)}${8-ri}`,{color:c===c.toUpperCase()?'w':'b',type:c.toLowerCase()});f++}});return out}
function order(){const files=userColor==='w'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=userColor==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>`${f}${r}`))}
function renderBoard(){if(!chess){board.replaceChildren();return}const pieces=parse(chess.fen()),frag=document.createDocumentFragment();for(const name of order()){const file=name.charCodeAt(0)-97,rank=Number(name[1]),sq=document.createElement('button');sq.type='button';sq.dataset.square=name;sq.className=`battle-square ${(file+rank)%2===1?'light':'dark'}${selected===name?' selected':''}`;const p=pieces.get(name);if(p){const img=document.createElement('img');img.className='battle-piece';img.src=`assets/pieces/${p.color}${p.type}.png`;img.alt='';sq.appendChild(img)}frag.appendChild(sq)}board.replaceChildren(frag);if(selected&&state?.status==='active')for(const m of chess.moves({square:selected,verbose:true}))board.querySelector(`[data-square="${m.to}"]`)?.classList.add('target')}
function uci(move){return `${move.from}${move.to}${move.promotion||''}`}
function loadPuzzleFromState(){selected=null;if(!state?.puzzle){chess=null;renderBoard();return}chess=new Chess(state.puzzle.fen);userColor=chess.turn();for(const m of state.moves||[]){try{chess.move({from:m.move.slice(0,2),to:m.move.slice(2,4),promotion:m.move[4]||'q'})}catch{}}renderBoard()}
function renderMeta(){if(!state){$('battleStatus').textContent=searching?'جارٍ البحث عن منافس…':'ابدأ البحث عن منافس.';return}$('battleMyScore').textContent=String(state.score??0);$('battleOpponentScore').textContent=String(state.opponentScore??0);$('battleMyMisses').textContent=String(state.misses??0);$('battleOpponentMisses').textContent=String(state.opponentMisses??0);$('battleMyRating').textContent=`${state.rating??1200} نقطة Battle`;$('battleOpponentRating').textContent=`${state.opponentRating??1200} نقطة Battle`;$('battleOpponentName').textContent=state.opponentName||'الخصم';$('battleMeName').textContent=player.name||'أنت';$('battlePuzzleBadge').textContent=state.puzzle?`لغز ${Number(state.puzzleIndex||0)+1} · ${state.puzzle.rating||''}`:'انتهت السلسلة';if(state.status==='active')$('battleStatus').textContent='حل أسرع من خصمك. كل حل صحيح = نقطة.';else if(state.winnerPlayerId===player.id)$('battleStatus').textContent='فزت في Puzzle Battle.';else if(!state.winnerPlayerId)$('battleStatus').textContent='انتهت Battle بالتعادل.';else $('battleStatus').textContent='انتهت Battle بفوز الخصم.';$('battleJoin').disabled=state.status==='active';$('battleCancel').disabled=true;tickClock()}
function tickClock(){const end=state?.endsAt?Date.parse(state.endsAt):0;const left=state?.status==='active'?Math.max(0,end-Date.now()):0;const sec=Math.ceil(left/1000);$('battleClock').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(state?.status==='active'&&left<=0)void refreshState()}
async function refreshState(){if(!battleId)return;try{state=await rpc('v3_get_puzzle_battle_state',{p_battle_id:battleId});loadPuzzleFromState();renderMeta()}catch(e){console.error(e)}}
async function join(){if(searching||state?.status==='active')return;searching=true;$('battleJoin').disabled=true;$('battleCancel').disabled=false;$('battleStatus').innerHTML='جارٍ البحث <span class="battle-searching"><i></i><i></i><i></i></span>';const attempt=async()=>{try{const rows=await rpc('v3_join_puzzle_battle');const r=Array.isArray(rows)?rows[0]:rows;if(r?.battle_id){searching=false;clearInterval(searchTimer);battleId=r.battle_id;const u=new URL(location.href);u.searchParams.set('battle',battleId);history.replaceState({},'',u);await refreshState();pollTimer=setInterval(refreshState,1500);return true}}catch(e){console.error(e);searching=false;$('battleStatus').textContent='تعذر بدء Puzzle Battle.'}$('battleJoin').disabled=searching;$('battleCancel').disabled=!searching;return false};if(await attempt())return;searchTimer=setInterval(attempt,2200)}
board.addEventListener('click',async e=>{if(!chess||state?.status!=='active'||chess.turn()!==userColor)return;const el=e.target.closest('.battle-square');if(!el)return;const sq=el.dataset.square,p=chess.get(sq);if(!selected){if(p?.color===userColor){selected=sq;renderBoard()}return}if(sq===selected){selected=null;renderBoard();return}if(p?.color===userColor){selected=sq;renderBoard();return}let move;try{move=chess.move({from:selected,to:sq,promotion:'q'})}catch{}if(!move){selected=null;renderBoard();return}const value=uci(move);chess.undo();selected=null;board.style.pointerEvents='none';try{state=await rpc('v3_puzzle_battle_move',{p_battle_id:battleId,p_move_uci:value});loadPuzzleFromState();renderMeta()}catch(err){console.error(err);await refreshState()}finally{board.style.pointerEvents=''}});
$('battleJoin').addEventListener('click',join);$('battleCancel').addEventListener('click',async()=>{searching=false;clearInterval(searchTimer);try{await rpc('v3_cancel_puzzle_battle_queue')}catch{}$('battleJoin').disabled=false;$('battleCancel').disabled=true;$('battleStatus').textContent='تم إلغاء البحث.'});
theme();battleId=new URLSearchParams(location.search).get('battle');if(battleId){await refreshState();if(state?.status==='active')pollTimer=setInterval(refreshState,1500)}else{chess=new Chess();userColor='w';renderBoard()}clockTimer=setInterval(tickClock,250);window.addEventListener('pagehide',()=>{clearInterval(searchTimer);clearInterval(pollTimer);clearInterval(clockTimer)});
