revoke all on function public.v2_my_player_id() from public, anon;
revoke all on function public.v2_send_friend_request(uuid) from public, anon;
revoke all on function public.v2_respond_friend_request(uuid,boolean) from public, anon;
revoke all on function public.v2_remove_friend(uuid) from public, anon;
revoke all on function public.v2_set_block(uuid,boolean) from public, anon;
revoke all on function public.v2_send_challenge(uuid,integer,integer,boolean,text) from public, anon;
revoke all on function public.v2_respond_challenge(uuid,boolean) from public, anon;
revoke all on function public.v2_mark_notification_read(uuid) from public, anon;
revoke all on function public.v2_submit_puzzle_attempt(uuid,boolean,integer,integer,boolean) from public, anon;
revoke all on function public.v2_complete_lesson(uuid,integer) from public, anon;
revoke all on function public.v2_create_club(text,text) from public, anon;
revoke all on function public.v2_join_club(uuid) from public, anon;
revoke all on function public.v2_post_club_message(uuid,text) from public, anon;
revoke all on function public.v2_send_message(uuid,text) from public, anon;

grant execute on function public.v2_my_player_id() to authenticated;
grant execute on function public.v2_send_friend_request(uuid) to authenticated;
grant execute on function public.v2_respond_friend_request(uuid,boolean) to authenticated;
grant execute on function public.v2_remove_friend(uuid) to authenticated;
grant execute on function public.v2_set_block(uuid,boolean) to authenticated;
grant execute on function public.v2_send_challenge(uuid,integer,integer,boolean,text) to authenticated;
grant execute on function public.v2_respond_challenge(uuid,boolean) to authenticated;
grant execute on function public.v2_mark_notification_read(uuid) to authenticated;
grant execute on function public.v2_submit_puzzle_attempt(uuid,boolean,integer,integer,boolean) to authenticated;
grant execute on function public.v2_complete_lesson(uuid,integer) to authenticated;
grant execute on function public.v2_create_club(text,text) to authenticated;
grant execute on function public.v2_join_club(uuid) to authenticated;
grant execute on function public.v2_post_club_message(uuid,text) to authenticated;
grant execute on function public.v2_send_message(uuid,text) to authenticated;
